### ISSUE TITLE
Barricades.dat 

### ISSUE THREAD

**Issue by art1fact** [SmartlyDressedGames/Unturned#10]
What it can be?
http://i.imgur.com/79ZX4ME.png

**Comment by cartman-2000** [comment]
Do you have any modded barricade type stuff on the server? I've seen some of the modded barricades leak stuff into the barricades file, but I've never seen one get that big before.

**Comment by art1fact** [comment]
I don't have any of modded barricades. You can see all my installed mods here:
http://steamcommunity.com/sharedfiles/filedetails/?id=468097331
