### ISSUE TITLE
Server "Lag"/Connection Issues

### ISSUE THREAD

**Issue by Airwarfare** [SmartlyDressedGames/Unturned#24]
With the latest version of Unturned for every server I've been on so far and from what I've heard from other people have experienced this issue its hard to explain and there's a lot of things that go with it so bear with me.

The client will remain in one place for everyone else but on there screen they can move around this makes it so that when the player is trying to pick up items they cant pick them up because the server thinks they're somewhere else. This also happens to be why some people cant see bases since the server thinks they're somewhere else why would it need to render, and also some people report "invisible" zombies which is really the server thinking they're in that said spot and a zombie attacks them while on the clients screen they're somewhere else

Another issue which I can't tell is related is that sometimes you will get a weird stutter effect when walking I can't figure out what causes this

all the issues listed above are fixed simply by disconnecting and reconnecting but its annoying because it glitches sometimes while in gun fights etc.

this still occurs for Unturned 3.14.1.0

Update : I believe this issue is related to the STEAMPS3 - AsyncTCPSocket created and destoryed messages that will appear in console, is there anyway to fix/disable this?

**Comment by Airwarfare** [comment]
Update : I believe this issue is related to the STEAMPS3 - AsyncTCPSocket created and destoryed messages that will appear in console, is there anyway to fix/disable this?

**Comment by falsechicken** [comment]
"STEAMPS3 - AsyncTCPSocket created and destroyed" is caused by server lag. I do not think this is the cause of any problems as I have seen this often but only when the server cannot keep up. Its a symptom not a cause.
