### ISSUE TITLE
Overloaded container bug is still an issue.

### ISSUE THREAD

**Issue by cartman-2000** [SmartlyDressedGames/Unturned#4]
The barricade vanishing bug due to overloaded containers(lockers/crates having over a certain number of items in them, around 20-26 items.) is still an issue on server's. At the current point in time the bug only affects MP server's, not singleplayer.

It is possible to fix a map that has the problem, currently, but you would have to load the map up into singleplayer to fix the offending container(s), either destroying them, or taking items out of them. I have to do this on my servers at least once or twice a week.

I've been able to reproduce this bug consistently(100% of the time.) in my testing on my test server by stuffing a locker full of 1x1 sized items.

http://steamcommunity.com/app/304930/discussions/9/613956964598519401/

**Comment by SDGNelson** [comment]
Wow 24 days late, a new record! This is on my to-do list for tomorrow.

Add me on Steam for quicker responses haha: http://steamcommunity.com/profiles/76561198036822957/

**Comment by cartman-2000** [comment]
After dealing with this bug some more on my server's over the past month or so, It would seem that the problem is in the server side code, possibly with how the container data is formatted to be sent to the client.

**Comment by cartman-2000** [comment]
I can confirm that the bug has been fixed in the v3.11.1.0 update.
