### ISSUE TITLE
Recording owner on all structures as you do with lockers.

### ISSUE THREAD

**Issue by Mashrien** [SmartlyDressedGames/Unturned#7]
I'm the one that was bugging Freaky about implementing a form of LogBlock and possible grief-protection (so only owners/group-members were able to destroy your structures)

Would it be possible for you to record the owner of all placed entities rather than just lockers/doors?

**Comment by SDGNelson** [comment]
This was discussed with Sven earlier today. Once the Steam classes are moved into the Platform system I want to change user identification to an IUserID interface which will be serialized with things like this when the conversion is made.

**Comment by Mashrien** [comment]
Sweet. At that point implementing logging, if not protection, should be fairly straightforward.

Thanks for the reply Nelson. :+1:
